Fix build on other architectures
openshift/ironic-agent-image pull request #23
Opened 2021-11-02 21:04 UTC by yselkowitz

This creates arch-specific package lists to handle those packages which are not available on all architectures.

/cc @elfosardo

2021-11-02 23:54 UTC, yselkowitz commented
/retest

2021-11-03 02:30 UTC, yselkowitz commented
Failure seems unrelated
/retest

2021-11-03 08:33 UTC, elfosardo commented
/retest

2021-11-03 08:53 UTC, elfosardo requested changes

2021-11-03 08:53 UTC, elfosardo commented on packages-list.ocp-aarch64
> +efibootmgr
we should leave efibootmgr and efivar in the general list, only biosdevname is going to be installed for x86_64

2021-11-03 13:30 UTC, yselkowitz commented on packages-list.ocp-aarch64
> +efibootmgr
ppc64le does not have those.

2021-11-03 14:10 UTC, elfosardo commented on packages-list.ocp-aarch64
> +efibootmgr
we don't build ironic-agent for ppc64le
https://github.com/openshift/ocp-build-data/blob/openshift-4.10/images/ironic-agent.yml

2021-11-03 14:18 UTC, yselkowitz commented on packages-list.ocp-aarch64
> +efibootmgr
Which appears to be an oversight, because we do build the rest of Ironic for ppc64le, and therefore this should be enabled as well (and is already in my ocp-build-data patch which is waiting on this).

2021-11-03 16:12 UTC, elfosardo commented on packages-list.ocp-aarch64
> +efibootmgr
this is not an oversight, it was done on purpose
I sent you a message on slack with more details

2021-11-03 16:42 UTC, elfosardo commented
/lgtm

2021-11-04 09:41 UTC, elfosardo commented
/retest

2021-11-04 13:16 UTC, dtantsur commented
/approve
/retest

2021-11-04 15:39 UTC, merged